---
title: "Climate Vulnerability Index for Salmon"
output:
  html_document:
    df_print: paged
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = F, warning = F, message = F)

#load packages and set root project directory

library(here)
library(tidyverse)
library(stars)   #package for data cubes (multi-dimensional spatial arrays)
library(ncdf4)
library(sf)      #spatial features
library(wesanderson)  #colour palettes
`%notin%` <- Negate(`%in%`)
library(gridExtra)  #for multi-panel ggplots
library(kableExtra)
library(units)
library(viridis)

setwd(here())

load(here("freshwater", "output", "2024-08-20_output.Rdata"))


```


```{r}
# Colour palette for plotting
col_pal <- wes_palette("Darjeeling1")

## periods to run for analysis
t_periods <- c("hist", "mid")

#vector of indicator names for analysis
PCIC_indies <- c("peakFlowAmt",     #ANNUAL peak flow amount 
                 "peakFlowDay",   #ANNUAL date of peak flow during year
                 "POT19freq",    #ANNUAL frequency of days above 19 degrees
                 "POT19dur",      #ANNUAL spell lenght of days above 19 degrees
                 "lowQ05",       #ANNUAL frequency of low flow events
                 "highQ95"       #ANNUAL frequency of high flow events
                 )


```


# Summarize PCIC indicators by CU

### Flow indicators
peakQmag - annual maximum peak flow  
peakQday - date of maximum peak flow in the year  
highQ95 - frequency of high flow events  
lowQ05 - frequency of low flow events  


```{r, comment=NA, warning=FALSE,message=FALSE, results="asis"}
flow_indies <- c("peakQmag_year", "peakQday_year", "highQ95_year", "lowQ05_year")

flow_stats <- PCIC_stats %>%
  select(c("spp", "cu", "cuid"), contains(c(flow_indies)))

for (a in 1:length(flow_indies)) {
  flow_attr <- select(flow_stats, contains(flow_indies[a])) %>%
    mutate(attr = flow_indies[a], .before = everything()) %>%
    rename_with(~str_replace(., paste0( flow_indies[a], "."), ""))
  
  cat("\n", flow_indies[a])
  print(kable(flow_attr))
  cat("\n\n")
}



## annual maximum peak flow
ggplot(flow_stats) +
  geom_boxplot(aes(y=peakQmag_year.diff.mean, x = spp)) 
ggplot(flow_stats) +
  geom_boxplot(aes(y=peakQmag_year.prct_change.mean, x = spp)) 

ggplot(flow_stats) +
  geom_boxplot(aes(y=peakQday_year.diff.mean, x = spp)) 
#kable(PCIC.CU_diff)

ggplot(flow_stats) +
  geom_boxplot(aes(y=highQ95_year.diff.mean, x = spp)) 
ggplot(flow_stats) +
  geom_boxplot(aes(y=highQ95_year.prct_change.mean, x = spp)) 
```

## Temperature indicators  
POT19freq - frequency of days above 19deg  
POT19dur - length of consecutive days above 19 degrees  


```{r, comment=NA, warning=FALSE,message=FALSE, results="asis"}

temp_indies <- c("POT19freq_year", "POT19dur_year")

temp_stats <- PCIC_stats %>%
  select(c("spp", "cu", "cuid"), contains(c(temp_indies))) %>%
  arrange(POT19freq_year.diff.mean, decreasing = TRUE)

for (a in 1:length(temp_indies)) {
  temp_attr <- select(temp_stats, contains(temp_indies[a])) %>%
    mutate(attr = temp_indies[a], .before = everything()) %>%
    rename_with(~str_replace(., paste0( temp_indies[a], "."), ""))
  
  cat("\n", temp_indies[a])
  print(kable(temp_attr))
  cat("\n\n")
}

ggplot(temp_stats) +
  geom_boxplot(aes(y=POT19freq_year.diff.mean, x = spp)) 

ggplot(temp_stats) +
  geom_boxplot(aes(y=POT19dur_year.diff.mean, x = spp))



```


# CU PCIC Vulnerability Output

```{r, echo = FALSE, comment=NA, warning=FALSE,message=FALSE, results="asis"}
sf_use_s2(FALSE)  #geometry interpretation - set to FALSE to avoid error
cu_rmd <- arrange(cu_run, Species) %>%
  filter( Species == "Coho")

for(i in 1:nrow(cu_rmd)) {
  
  cu_pick <- cu_rmd$cuid[i]
  
  cat(" \n### ", cu_rmd$cuname[i], " - ", cu_rmd$Species[i], "\n")

  cu_flow <- filter(flow_stats, cuid == cu_pick) %>%
    ungroup() %>%
    select(-c("spp", "cuid")) %>%
    drop_units()
  
  cu_temp <- filter(temp_stats, cuid == cu_pick) %>%
    ungroup() %>%
    select(-c("spp", "cuid")) %>%
      drop_units()
  
  cu_q95mag <- select(cu_flow, contains(flow_indies[1])) %>%
    mutate(attr = flow_indies[1], .before = everything()) %>%
    rename_with(~str_replace(., flow_indies[1], ""))
  
  cu_q95high <- select(cu_flow, contains(flow_indies[3])) %>%
    mutate(attr = flow_indies[3], .before = everything()) %>%
    rename_with(~str_replace(., flow_indies[3], ""))
  
  cu_19freq <- select(cu_temp, contains(temp_indies[1])) %>%
    mutate(attr = temp_indies[1], .before = everything()) %>%
    rename_with(~str_replace(., temp_indies[1], ""))
  
  print(kable(rbind(cu_q95mag, cu_q95high, cu_19freq)))
  cat("\n\n")
  
  cu_boundary.i <- filter(cu_boundary, CUID == cu_pick)
  
  PCIC.CU <- PCIC[cu_boundary.i]
  
  PCIC.CU.temp <- PCIC.CU[temp_indies]
  PCIC.CU.flow <- PCIC.CU[flow_indies]
  

  p1 <- ggplot() +
  geom_stars(data = r) +
  facet_grid(new_dim~time) +
  theme_minimal() +
  scale_fill_viridis() +
  geom_sf(data = cu_boundary.i, fill = NA, color = "black")
  
  r <- drop_units(PCIC.CU.flow) %>%
      st_redimension()
  names(r) = "value"
  
  p2 <- ggplot() +
  geom_stars(data = r) +
  facet_grid(new_dim~time) +
  theme_minimal() +
  scale_fill_viridis() +
  geom_sf(data = cu_boundary.i, fill = NA, color = "black")
  
  print(p1)
  print(p2)
      
  # nbr <- 8
  # plot(PCIC.CU.flow[1], main = "Max Flows")#, nbreaks = nbr, col = viridis(nbr - 1))
  # plot(PCIC.CU.flow[3], main = "Freq High Flows")#, nbreaks = nbr, col = viridis(nbr - 1))
  # plot(PCIC.CU.temp[1], main = "Days >19Deg")#, nbreaks = nbr, col = viridis(nbr - 1))
  # 
  cat(" \n\n\n\n\\pagebreak\n")
}


```
