---
title: "Upstream Migration"
output: html_document
date: "2024-12-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

#load packages
library(gridExtra)  #for multi-panel ggplots
library(kableExtra)
library(units)

```


```{r, comment=NA, warning=FALSE,message=FALSE, results="asis"}

theme_custom <- function(base_size = 14) {
  theme_bw(base_size = base_size) %+replace%
    theme(
      # L'ensemble de la figure
      plot.title = element_text(size = rel(1), face = "bold", margin = margin(0,0,5,0), hjust = 0),
      # Zone où se situe le graphique
      panel.grid.minor = element_blank(),
      panel.border = element_blank(),
      # Les axes
      axis.title = element_text(size = rel(0.85), face = "bold"),
      axis.text = element_text(size = rel(0.70), face = "bold"),
      #axis.line = element_line(color = "black", arrow = arrow(length = unit(0.3, "lines"), type = "closed")),
      axis.line = element_line(color = "black"),
      # La légende
      legend.title = element_text(size = rel(0.85), face = "bold"),
      legend.text = element_text(size = rel(0.70), face = "bold"),
      legend.key = element_rect(fill = "transparent", colour = NA),
      legend.key.size = unit(1.5, "lines"),
      legend.background = element_rect(fill = "transparent", colour = NA),
      # Les étiquettes dans le cas d'un facetting
      strip.background = element_rect(fill = "#17252D", color = "#17252D"),
      strip.text = element_text(size = rel(0.85), face = "bold", color = "white", margin = margin(5,0,5,0))
    )
}

theme_set(theme_custom())
```



Create outputs of migration paths and summary statistics

```{r}

PCIC_hist <- filter(PCIC_day, year(time) == 1985)
PCIC_proj <- filter(PCIC_day, year(time) == 2055)


for(c in 1:n.CUs) {
  path_cu <- path_list[[c]]
  cuid_i <- names(path_list)[c]
  
  cu_boundary_i <- cu_boundary[cu_boundary$CUID == cuid_i,]
  
  timing_s <- cu_timing$rt_start[cu_timing$cuid == cuid_i]
  timing_e <- cu_timing$rt_end[cu_timing$cuid == cuid_i]
  
  PCIC_hist_cu <- PCIC_hist[path_cu] %>%
    filter(yday(time) >= timing_s, yday(time) <= timing_e) %>%
    aggregate(by = "year", FUN = median)
  
  PCIC_proj_cu <- PCIC_proj[path_cu] %>%
    filter(yday(time) >= timing_s, yday(time) <= timing_e) %>%
    aggregate(by = "year", FUN = median)
  
  #PCIC_diff_cu <- apply(PCIC_proj_cu - PCIC_hist_cu[1]
  
  tq_hist_t <- quantile(PCIC_hist_cu$tw_day, na.rm = T)
  fq_hist_t <- quantile(PCIC_hist_cu$flow_day, na.rm = T)
  
  tq_proj_t <- quantile(PCIC_proj_cu$tw_day, na.rm = T)
  fq_proj_t <- quantile(PCIC_proj_cu$flow_day, na.rm = T)
  
  if(c > 1) {
    tq_hist <- bind_rows(tq_hist, tq_hist_t)
    fq_hist <- bind_rows(fq_hist, fq_hist_t)
    tq_proj <- bind_rows(tq_proj, tq_proj_t)
    fq_proj <- bind_rows(fq_proj, fq_proj_t)
  }
  if(c ==1) {
    tq_hist <- tq_hist_t
    fq_hist <- fq_hist_t
    tq_proj <- tq_proj_t
    fq_proj <- fq_proj_t
  }
  
    p.list <- list()
    
  for(d in 1:2) {
  
    p.list[[d]] <- ggplot() +
      geom_stars(data = PCIC_hist_cu[d]) +
      scale_fill_viridis() +
      theme_minimal() +
      geom_sf(data = cu_boundary_i, color = "black", alpha = 0.2) +
      geom_sf(data = st_zm(path_cu))
    
    p.list[[d+2]] <- ggplot() +
      geom_stars(data = PCIC_proj_cu[d]) +
      scale_fill_viridis() +
      theme_minimal() +
      geom_sf(data = cu_boundary_i, color = "black", alpha = 0.2) +
      geom_sf(data = st_zm(path_cu))
  }

  cat(" \n### ", cu_run$cuname[c], " - ", cu_run$Species_simple[c], "\n")
  cat(" \n Migration start date:", timing_s, "     Migration end date:", timing_e)
  cat(" \n  Migration distance = ", round(path_distance[c]/1000), "km")
  cat(" \n  Migration elevation = ", path_elev[c],  "m")
  
  cat(" \nQuantiles:               0%  25%  50%  75%  100% \n")
  cat(" \n Temperature historic :", round(tq_hist_t, 1))
  cat(" \n Temperature projected:", round(tq_proj_t, 1))
  cat(" \n Temperature difference:", round(tq_proj_t- tq_hist_t, 1))
  cat(" \n Flow        historic :", round(fq_hist_t, 1))
  cat(" \n Flow        projected:", round(fq_proj_t, 1))
  cat(" \n Flow        difference:", round(fq_proj_t- fq_hist_t, 1))
  
  grid.arrange(p.list[[1]], p.list[[3]], nrow = 1, ncol = 2)
  grid.arrange(p.list[[2]], p.list[[4]], nrow = 1, ncol = 2)
  
  cat(" \n\n\\pagebreak\n")  
  
}

row.names(tq_hist) <- cuid
row.names(fq_hist) <- cuid
row.names(tq_proj) <- cuid
row.names(fq_proj) <- cuid

# ggplot() +
#   geom_stars(data = PCIC_plot_cu) +
#   geom_sf(data = cu_boundary[cu_boundary$CUID == cuid[14],], alpha = 0.2) +
#   geom_sf(data = st_zm(path_list[[14]])) 


```

