---
title: "CU Climate Vulnerability Profile"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(kableExtra)
```

```{r}

i <- 1

cu_boundary_i <- cu_boundary[cu_boundary$CUID == cuid[i], ]
cu_pick <- cu_run[cu_run$cuid == cuid[i],]
FWA_cu <- st_crop(FWA_Fr_high, cu_boundary_i)
# Subset CU migration path
path_CU <- path_list[[i]]

#subset nuseds observations
nuseds_CU <- nuseds_Fr[nuseds_Fr$FULL_CU_IN == cu_run$FULL_CU_IN[i],]

fw_indies_CU <- fw_acc_indies[stream_cu_picks[,i],] 

cu_boundary_table <- all_CU_stats[i,]


cu_boundary_table <- cu_boundary_table %>%
  mutate(length_sum = length_sum/1000) %>%
  select(n_streams, length_sum, ThiPI_9_45_3, Tw_rate, MADprop_8_diff,
         MADprop_win_diff, peakQday_diff, CT_anad_mean) %>%
  rename("Number of stream segments" = n_streams,
         "Total stream length (km)" = length_sum,
         "7DEC High T 2041-2060" = ThiPI_9_45_3,
         "Temperature Rate of Change (deg C/10y)" = Tw_rate,
         "Change in August flow as %MAD" = MADprop_8_diff,
         "Change in winter flow as %MAD" = MADprop_win_diff,
         "Change in peak flow day"       = peakQday_diff,
         "Cumulative threat score"       = CT_anad_mean
  )


```



`r cu_pick$CU_NAME`
=====================================


Column {data-width=650}
-----------------------------------------------------------------------





### Stream habitat cumulative stressor score

```{r}

ggplot() +
    geom_sf(data = fw_indies_CU, aes(color = CT_anad), linewidth = 1.) +
    scale_color_viridis(limits = c(0,5.5)) +
    geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
    coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
             ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
    labs(subtitle = paste("Cumulative stressor score (anadromous)"), color = "Threat Score") +
    theme_minimal()
```

### Projected Temperature
```{r}

ggplot() +
    #geom_sf(data = st_zm(FWA_cu), color = "grey", alpha = 0.4) +
    #geom_stars(data = PCIC_Aug_CU_proj["tw_month"]) +
    #scale_fill_gradientn(colours = wesanderson::wes_palette("Zissou1", 100, type = "continuous")) +
    geom_sf(data = fw_indies_CU, aes(color = Tav_9_45_3), linewidth = 1.) +
    scale_color_gradientn(colours = wesanderson::wes_palette("Zissou1", 100, type = "continuous"),
                          limits = c(5,25)) +
    geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
    coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
             ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
    labs(subtitle = paste("Mean 7DEC, 2041-2060"), color = "T (deg C)") +
    theme_minimal()
```

### Mean Annual Discharge

```{r}
 max_hist_flow <- max(fw_indies_CU$mean_flow_m3s_17_1, na.rm = T)
  max_proj_flow <- max(fw_indies_CU$mean_17_40, na.rm = T)
  max_plot_flow <- max(max_hist_flow, max_proj_flow)

 ggplot() +
    geom_sf(data = fw_indies_CU, aes(color = mean_flow_m3s_17_1), linewidth = 1.) +
    scale_color_viridis(limits = c(0, max_plot_flow)) +
    geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
    coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
             ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
    labs(subtitle = paste("Mean annual discharge, 1981-2000"), color = "Flow (m3/s)") +
    theme_minimal()
```

Column {data-width=350}
-----------------------------------------------------------------------

### CU Summary Statistics

```{r}

  print(kable(cu_boundary_table))

```






