---
title: "2_FW_spawning_report"
output:
  html_document:
    toc: true
    number-sections: true
params:
  FULL_CU_IN: "CK-3"

---

```{r custom theme, echo = FALSE, message = F, warning = F}

library(viridis)
library(gt)        # nice tables
library(patchwork) # plot layouts

knitr::opts_chunk$set(message = F, echo = F, warning = F)

theme_cvis <- function(base_size = 14) {
  theme_bw(base_size = base_size) %+replace%
    theme(
      # L'ensemble de la figure
      plot.title = element_text(size = rel(1), face = "bold", margin = margin(0,0,5,0), hjust = 0),
      # Zone où se situe le graphique
      panel.grid.minor = element_blank(),
      panel.border = element_blank(),
      # Les axes
      axis.title = element_text(size = rel(0.85), face = "bold"),
      axis.text = element_text(size = rel(0.70), face = "bold"),
      axis.line = element_line(color = "black"),
      # La légende
      legend.title = element_text(size = rel(0.85), face = "bold"),
      legend.text = element_text(size = rel(0.70), face = "bold"),
      legend.key = element_rect(fill = "transparent", colour = NA),
      legend.key.size = unit(1.5, "lines"),
      legend.background = element_rect(fill = "transparent", colour = NA),
      # Les étiquettes dans le cas d'un facetting
      strip.background = element_rect(fill = "#17252D", color = "#17252D"),
      strip.text = element_text(size = rel(0.85), face = "bold", color = "white", margin = margin(5,0,5,0))
    )
}
theme_set(theme_cvis())
```


```{r subset CU}

#params$FULL_CU_IN <- "CK-17"
cu_i <- params$FULL_CU_IN
cu_run_i <- cu_run[cu_run$FULL_CU_IN == params$FULL_CU_IN,]
sp_pick <- cu_run$spp[cu_run$FULL_CU_IN == cu_i] #species abbr
sp_pick_bcfp <- spp_lookup$spp_abr_bcfp[spp_lookup$spp_abr == sp_pick] 

```



```{r spatial subset}

stream_cu_sub <- stream_cu_picks[,colnames(stream_cu_picks) == cu_i]
reaches_ENM_sub <- ENM_cu_picks[,colnames(ENM_cu_picks) == cu_i]

cu_boundary_i <- cu_boundary[cu_boundary$FULL_CU_IN == cu_i,]

#subset nuseds observations
nuseds_cu <- nuseds_Fr[nuseds_Fr$FULL_CU_IN == cu_i,]

fwModels_cu <- fwModels[stream_cu_sub,] %>%
  rename(keep_model_spawning = contains(paste0("model_spawning_", sp_pick_bcfp)),
         keep_model_rearing  = contains(paste0("model_rearing_", sp_pick_bcfp))) %>%
  mutate(model_rs = if_any(starts_with("keep_model"), ~ . == TRUE)) %>%#get boolean for model spawning and rearing
  select(-starts_with(c("model_spawning","model_rearing", "known_rearing", "known_spawning")))

# bcfpa_cu <- bcfpa[stream_cu_sub,] %>%
#   select(segmented_stream_id:mad_m3s,
#          contains(sp_pick_bcfp)) %>%  #subset model for CU species
#   rename(model_spawning = starts_with("model_spawning"),
#          model_rearing  = starts_with("model_rearing")) %>%
#   mutate(model_rs = if_any(starts_with("model"), ~ . == TRUE))  #get boolean for model spawning and rearing

#bcfpa_cu_rs <- filter(bcfpa_cu, model_rs == TRUE)

# fwT_cu <- fwT[stream_cu_sub,] %>% 
#   left_join(select(bcfpa_cu, segmented_stream_id, model_rs), 
#             by = "segmented_stream_id") %>%
#   st_as_sf()
# 
# fwQ_cu <- fwQ[stream_cu_sub,] %>%
#   left_join(select(bcfpa_cu, segmented_stream_id, model_rs), 
#             by = "segmented_stream_id") %>%
#   st_as_sf()
# 
# fwct_cu<- fwct[stream_cu_sub,] %>%
#   left_join(select(bcfpa_cu, segmented_stream_id, model_rs), 
#             by = "segmented_stream_id") %>%
#   st_as_sf()


ENM_cu <- reaches_ENM_all[reaches_ENM_sub,]
  # select(linear_feature_id, segmented_stream_id, Shape_Length, Length_km,
  #        contains(sp_pick)) %>%
  # left_join(select(bcfpa_cu, segmented_stream_id, model_rs),
  #           by = "segmented_stream_id")


#read Temperature gauge locations
Tw_stations <- st_read(file.path(paths$climate, "Tw_stations.gdb"))

#watershed hydrologic regimes
watershed_flow <- st_read(file.path(paths$climate, "Ruzzante_low_flows", "watersheds.gpkg")) %>%
  left_join(select(stations_stats, ID, regime), by = c("ID" = "ID")) %>%
  mutate(regime = as.factor(regime)) %>%
  st_transform(3005)

#flow stations
stations_flow <- st_read(file.path(paths$climate, "Ruzzante_low_flows", "stations.gpkg")) %>%
  st_transform(3005)

```


### CU Data Summaries

```{r data tables}

fwR_cu <- fwR_all[[cu_i]] 

#make summary of stream statistics

fwR_cu$streams %>%
  gt() %>%
  tab_header(title = "CU Boundary Stream Statistics") %>%
  gt_split(col_slice_at = c("total_length_spawn", "cu_area"))

fwR_cu$streams %>%
  select(contains("nuseds")) %>%
  gt() %>%
  tab_header(title = "CU NUSEDS statistics")

fwR_cu$streams %>%
  select(contains("prop")) %>%
  gt() %>%
  tab_header(title = "Hydrologic Regime")

fwR_cu$CT %>% 
  gt() %>%
  tab_header(title = "Cumulative Threats")

fwR_cu$fwT %>%
  gt() %>%
  tab_header(title = "Stream Temp") 

fwR_cu$fwQlow %>%
  gt() %>%
  tab_header(title = "August flows - PCIC stream model") 

fwR_cu$ENM %>%
  gt() %>%
  tab_header(title = "ENM favourability")

# fwR_cu$wpQlow %>%
#   gt() %>%
#   tab_header(title = "August flows - statistical gauge model")

```



```{r make maps}

streams_p <- ggplot() +
    geom_sf(data = st_zm(fwModels_cu), aes(color = model_rs)) + 
    geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
    geom_sf(data = nuseds_cu, aes(color = SPECIES), alpha = 0.6) +
    coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
             ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
    labs(subtitle = paste(cu_run_i$CU_NAME), colour = "BC FishPass")


stream_indicator_plot <- function(fwModels, 
                                  variable = "CT_anad", 
                                  plot_title = "Indicator plot", 
                                  histogram_fill = "model_rs") {
  
  # Convert variable name to symbol for tidy evaluation
  var_sym <- sym(variable)
  hist_sym <- sym(histogram_fill)

  p1 <- ggplot() +
  geom_sf(data = fwModels, aes(color = !!var_sym), linewidth = 1.) +
  scale_color_viridis_c() + 
  geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
  coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
           ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
  labs(subtitle = plot_title)

  h1 <- ggplot(fwModels) +
  geom_vline(aes(xintercept = mean(!!var_sym, na.rm = T)), color = "red", linetype = "dashed") +
  labs(fill = "Rearing/spawning") +
  geom_text(aes(x = mean(!!var_sym, na.rm = T), y = 20, label = "mean"), color = "red") +
  geom_histogram(aes(x = !!var_sym, fill = !!hist_sym)) 

p1 / h1 +
  plot_layout(heights = c(3, 1))

}


#temperature plot
t_plot <- stream_indicator_plot(fwModels_cu, 
                                variable = "Tw8_9_45_3", 
                                plot_title = "August Mean Temperature - 2041-2060")

Q8_plot <- stream_indicator_plot(fwModels_cu, 
                                variable = "month_8_p40", 
                                plot_title = "M3s August flow - 2041-2060")

Q8deltaprop_plot <- stream_indicator_plot(fwModels_cu, 
                                variable = "Q8_deltaprop_p40", 
                                plot_title = "%change in August flow - 2041-2060")

ENM_col <- names(select(ENM_cu, contains("Fav_f.9_45_3")))[1]

ENM_plot <- stream_indicator_plot(ENM_cu, 
                                  variable = ENM_col,
                                  plot_title = "ENM favourability, 2041-2060",
                                  histogram_fill = "model_habitat_salmon")

ENM_col <- names(select(ENM_cu, contains("Fav_change_9_45_5")))[1]

ENM_diff_plot <- stream_indicator_plot(ENM_cu, 
                                  variable = ENM_col,
                                  plot_title = "ENM favourability change, 2081-2100",
                                  histogram_fill = "model_habitat_salmon")


t_plot
Q8_plot
Q8deltaprop_plot
ENM_plot
ENM_diff_plot


# 
# ts_hist_p <- ggplot() +
#   geom_sf(data = fwT_cu, aes(color = Tw8_0_00_0), linewidth = 1.) +
#   scale_color_gradientn(colours = wesanderson::wes_palette("Zissou1", 100, type = "continuous"),
#                         limits = c(5,25)) + 
#   geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
#   geom_sf(data = Tw_stations, color = "forestgreen", size = 0.5) +
#   coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
#            ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
#   labs(subtitle = paste("August T, Thermalscapes, 1981-2000"), color = "T (deg C)")
# 
# ts_hist_h <- ggplot(fwT_cu) +
#   geom_histogram(aes(x = Tw8_0_00_0, fill = model_rs)) +
#   geom_vline(aes(xintercept = mean(Tw8_0_00_0, na.rm = T)), color = "red", linetype = "dashed") +
#   labs(fill = "Modelled rearing/spawning")
# 
# ts_proj_p <- ggplot() +
#   geom_sf(data = fwT_cu, aes(color = Tw8_9_45_3), linewidth = 1.) +
#   scale_color_gradientn(colours = wesanderson::wes_palette("Zissou1", 100, type = "continuous"),
#                         limits = c(5,25)) + 
#   geom_sf(data = cu_boundary_i, color = "black", alpha = 0.3) +
#   geom_sf(data = Tw_stations, color = "forestgreen", size = 0.5) +
#   coord_sf(xlim = st_bbox(cu_boundary_i)[c(1,3)],
#            ylim = st_bbox(cu_boundary_i)[c(2,4)]) +
#   labs(subtitle = paste("August T, Thermalscapes, 2041-2060"), color = "T (deg C)")
# 
# ts_proj_h <- ggplot(fwT_cu) +
#   geom_histogram(aes(x = Tw8_9_45_3)) +
#   geom_vline(aes(xintercept = mean(Tw8_9_45_3, na.rm = T)), color = "red", linetype = "dashed") +
#   #geom_vline(aes(xintercept = median(Tw8_9_45_3, na.rm = T)), color = "blue", linetype = "dashed") +
#   geom_text(aes(x = mean(Tw8_9_45_3, na.rm = T), y = 20, label = "mean"), color = "red") 
# 


### ENM favourability within CU boundary


# 
# ENM_proj_p <- ggplot() +
#   geom_sf(data = ENM_cu, aes(color = .data[[plot_col]])) + 
#   geom_sf(data = cu_boundary_i, color = "black", alpha = 0.2) +
#   scale_color_viridis()
# 
# ENM_proj_h <- ggplot() +
#   geom_histogram(data = ENM_cu, aes(x = .data[[plot_col]])) 
# 
# plot_col <- names(select(ENM_cu, contains("Fav_change_9_45_5")))[1]
# ENM_diff_p <- ggplot() +
#   geom_sf(data = ENM_cu, aes(color = .data[[plot_col]])) + 
#   geom_sf(data = cu_boundary_i, color = "black", alpha = 0.2) +
#   scale_color_viridis()
# 
# ENM_diff_h <- ggplot() +
#   geom_histogram(data = ENM_cu, aes(x = .data[[plot_col]]))
# 
# ENM_plot <- stream_indicator_plot(ENM_cu, 
#                                   variable = "Fav_f.9_45_3",
#                                   plot_title = "ENM favourability, 2041-2060",
#                                   histogram_fill = "model_habitat_salmon")
# 
# ENM_diff_plot <- stream_indicator_plot(ENM_cu, 
#                                   variable = "Fav_change_9_45_5",
#                                   plot_title = "ENM favourability change, 2081-2100",
#                                   histogram_fill = "model_habitat_salmon")
# 
# 


# 
# cu_acc_p
# #hydro_day_plot / tw_day_plot
# ct_anad_p
# ct_anad_h
# ts_hist_p
# ts_hist_h
# ts_proj_p
# ts_proj_h
# # #rateT_p + rateT_h
# ENM_proj_p
# ENM_proj_h
# ENM_diff_p
# ENM_diff_h


```



